branches:
  except:
  - /^stage.*$/
sudo: required
env:
  global:
    - MINIO_VER="RELEASE.2019-09-26T19-42-35Z"
    - ALPINE_VER="3.10"
    - UID="2000"
    - GID="2000"
    - COMPOSE_HTTP_TIMEOUT="300"
    # - COVERALLS_SERVICE_NAME="travis-ci"
    # - COVERALLS_REPO_TOKEN=""
services: 
- docker
main: &main
      stage: Alpine
      os: linux
      dist: xenial # precise, trusty, xenial, bionic
      language: shell
      script:
        # create using: echo \"$(sed ':a;N;$!ba;s|\t|\\t|g' ./datajoint-dev.pem | sed 's| |\\ |g' | sed 's|"|\\"|g' | sed ':a;N;$!ba;s|\n|\\n|g')\"
        - mkdir -p /home/travis/keys
        - echo $DJ_PRIVATE_KEY > /home/travis/keys/datajoint-dev.pem 2>&1
        - sed -i 's|\\n|\n|g' /home/travis/keys/datajoint-dev.pem
        - sed -i 's|\\"|"|g' /home/travis/keys/datajoint-dev.pem
        - sed -i 's|\\ | |g' /home/travis/keys/datajoint-dev.pem
        - sed -i 's|\\t|\t|g' /home/travis/keys/datajoint-dev.pem
        - echo $DJBOT_PRIVATE_KEY > /home/travis/keys/datajointbot-test.pem 2>&1
        - sed -i 's|\\n|\n|g' /home/travis/keys/datajointbot-test.pem
        - sed -i 's|\\"|"|g' /home/travis/keys/datajointbot-test.pem
        - sed -i 's|\\ | |g' /home/travis/keys/datajointbot-test.pem
        - sed -i 's|\\t|\t|g' /home/travis/keys/datajointbot-test.pem
        - sudo chmod u-x,g-rwx,o-rwx /home/travis/keys/datajointbot-test.pem
        - eval "$(ssh-agent -s)"
        - ssh-add /home/travis/keys/datajointbot-test.pem
        - ./serve.sh up TRAVIS
jobs:
  include:
    - stage: "Lint: Syntax"
      language: python
      install:
        - pip install flake8
      script:
        - |
          flake8 datajoint_connection_hub --count --select=E9,F63,F7,F82 --show-source \
          --statistics
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.7"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.6"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.5"
      - MYSQL_VER: "5.7"
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "8.0"
    - <<: *main
      env:
      - PY_VER: "3.8"
      - MYSQL_VER: "5.6"
    - stage: "Lint: Style"
      language: python
      install:
        - pip install flake8
      script:
        - |
          flake8 --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E722,F401,W605 \
          datajoint_connection_hub --count --max-complexity=62 --max-line-length=127 \
          --statistics
