version: '2.2'
x-net: &net
  networks:
      - main
services:
  app:
    <<: *net
    image: datajoint/pydev:${PY_VER}-alpine${ALPINE_VER}
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      hub-redirect:
        condition: service_healthy
      fakeservices.datajoint.io:
        condition: service_healthy
    environment:
      # - DJ_HOST=db
      - DJ_HOST=hub://fakeservices.datajoint.io/datajoint/travis
      - DJ_USER=root
      - DJ_PASS=simple
      # - DJ_TEST_HOST=db
      - DJ_TEST_HOST=hub://fakeservices.datajoint.io/datajoint/travis
      - DJ_TEST_USER=datajoint
      - DJ_TEST_PASSWORD=datajoint
      # If running tests locally, make sure to add entry in /etc/hosts for 127.0.0.1 fakeservices.datajoint.io
      - S3_ENDPOINT=fakeservices.datajoint.io:9000
      - S3_ACCESS_KEY=datajoint
      - S3_SECRET_KEY=datajoint
      - S3_BUCKET=datajoint-test
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=datajoint
      - DISPLAY
    working_dir: /src
    command: >
      /bin/sh -c
       "
        mkdir /home/dja/datajoint-python;
        git clone -b plugin --single-branch https://github.com/guzman-raphael/datajoint-python.git /home/dja/datajoint-python
        pip install --user nose nose-cov coveralls ptvsd twine /home/dja/datajoint-python .;
        pip freeze | grep datajoint;
        ## You may run the below tests once sh'ed into container i.e. docker exec -it datajoint-python_app_1 sh        
        # nosetests -vs --tests=/home/dja/datajoint-python/tests; #run DataJoint's tests
        # nosetests -vsw tests; #run plugin tests
        # nosetests -vs --tests=tests.test_external_class:test_insert_and_fetch; #run specific basic test
        # nosetests -vs --tests=tests.test_fetch:TestFetch.test_getattribute_for_fetch1; #run specific Class test
        ## Interactive Jupyter Notebook environment
        jupyter notebook &
        ## Remote debugger
        while true;
        do python -m ptvsd --host 0.0.0.0 --port 5678 --wait .;
        sleep 2;
        done;
       "
    ports:
      - "8888:8888"
      - "5678:5678"
    user: ${UID}:${GID}
    volumes:
      - .:/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Additional mounted notebooks may go here
  db:
    <<: *net
    image: datajoint/mysql:$MYSQL_VER
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    # ports:
    #   - "3306:3306"
    # To persist MySQL data
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
  minio:
    <<: *net
    environment:
      - MINIO_ACCESS_KEY=datajoint
      - MINIO_SECRET_KEY=datajoint
    image: minio/minio:$MINIO_VER
    # ports:
    #   - "9000:9000"
    # To persist MinIO data and config
    # volumes:
    #   - ./minio/data:/data
    #   - ./minio/config:/root/.minio
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://minio:9000/minio/health/live"]
      timeout: 5s
      retries: 60
      interval: 1s
  fakeservices.datajoint.io:
    <<: *net
    image: nginx:alpine
    environment:
      - URL=datajoint.io
      - SUBDOMAINS=fakeservices
      - MINIO_SERVER=http://minio:9000
      - REDIRECT_SERVER=http://hub-redirect:4000
      - MYSQL_SERVER=db:3306
    entrypoint: /entrypoint.sh
    healthcheck:
      test: wget --quiet --tries=1 --spider https://fakeservices.datajoint.io:443/minio/health/live || exit 1
      timeout: 5s
      retries: 300
      interval: 1s
    ports:
      - "9000:9000"
      - "443:443"
      - "4000:4000"
      - "3306:3306"
    volumes:
      - ./tests/nginx/base.conf:/base.conf
      - ./tests/nginx/nginx.conf:/nginx.conf
      - ./tests/nginx/entrypoint.sh:/entrypoint.sh
      - ./tests/nginx/fullchain.pem:/certs/fullchain.pem
      - ./tests/nginx/privkey.pem:/certs/privkey.pem
  hub-redirect:
    <<: *net
    image: node:13-alpine3.10
    working_dir: /
    entrypoint: node /app.js
    # ports:
    #   - "4000:4000"
    volumes:
      - ./tests/redirect/app.js:/app.js
    healthcheck:
      test: wget --quiet --tries=1 --spider http://hub-redirect:4000/status || exit 1
      timeout: 5s
      retries: 300
      interval: 1s
networks:
  main:
